### ISSUE TITLE
Create CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by payaldutta** [geekymeeky/Mausam#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I want to create a code of conduct file for those who are new to open source. @naman5665 @geekymeeky  Can I work on this under DCP'21.

**Comment by geekymeeky** [comment]
@payaldutta It's already [added](https://github.com/geekymeeky/Mausam/blob/main/CODE_OF_CONDUCT.md)
